### ISSUE TITLE
LightSync breaks upon uploading or testing builds

### ISSUE THREAD

**Issue by ghost** [MMMaellon/LightSync#1]
I used this alongside a few prefabs for my world and it causes errors of invalid objects. It is perfectly fine when unpacking the prefab with no issues.
![image](https://github.com/MMMaellon/LightSync/assets/116863714/6458c2e0-8703-4b94-9083-cd4884a68d20)
I tried to set it up inside and outside of the prefab individually and neither worked properly. **I hope that this does get resolved!**

**Comment by ghost** [comment]
It seems to have gotten worse where it seems that LightSync is completely impossible to make a test build with, even after unpacking prefabs.
![image](https://github.com/MMMaellon/LightSync/assets/116863714/3dbe5098-f7f5-4ee0-b64e-b9d18e2eb612)
![image](https://github.com/MMMaellon/LightSync/assets/116863714/36ac0bec-8f78-4f8a-98d6-177ce206b937)
![image](https://github.com/MMMaellon/LightSync/assets/116863714/411ddf8d-88d7-45b0-93f9-7c1e522dbaaf)
![image](https://github.com/MMMaellon/LightSync/assets/116863714/45bb1e1b-dfbe-47f8-9501-5fec40687096)
Looking at the code, it seems that this part is the issue
![image](https://github.com/MMMaellon/LightSync/assets/116863714/1eefe96f-8a6a-48c4-9f77-53603278e70c)
It seems that `_allowedBones` is conflicting with `allowedBones`.

**Comment by ghost** [comment]
Seems that quoting that section I mentioned completely fixed the problem for now as it gets fixed. it does create quite a few errors in the editor but works in-game
![image](https://github.com/MMMaellon/LightSync/assets/116863714/d7cb2265-0451-44cb-8409-01a668ea14bf)

**Update:** To further fix it; I quoted out the `#else` section entirely and there is not a single error from testing and everything seems to work as intended.
![image](https://github.com/MMMaellon/LightSync/assets/116863714/1764551c-8eb5-4d17-9e7b-d17171f8b2ea)
I hope this was useful for a patch to my issue!

**Comment by ghost** [comment]
It also seems that under `LightSyncEnhancementWithData` has something that does not exist on Android and causes errors, making Android compiling impossible.
![image](https://github.com/MMMaellon/LightSync/assets/116863714/9cb12b3b-481d-440e-be9c-175450abb515)
Commenting it out fixed the issue with no errors and allowed me to upload my world to VRChat.

**Comment by MMMaellon** [comment]
Interesting that the compiler flags seem to be different on Android. I wonder why. Also I'm surprised this didn't break anything else because I use those kinds of if statements everywhere. one of the design philosophies of LightSync is to over-engineer the editor scripts so that only the minimum is happening at runtime. I'll see if I can keep that else section commented out.

**Comment by MMMaellon** [comment]
Fixed by https://github.com/MMMaellon/LightSync/commit/75a1267c43c6d8b2455344be9dc3aa3fddd2189e
It means we get more warnings in the console, but it's better than completely breaking
