### ISSUE TITLE
Sync Defaults to Continous and Cannot be Changed En-Masse

### ISSUE THREAD

**Issue by Enverex** [MMMaellon/LightSync#3]
So defaulting to Continuous isn't too bad as it's been explained the script handles this internally, but it becomes an issue due to the whole "VRChat uses whatever the last setting is" resulting in it pushing other scripts to Continuous. The fix then would be to set the script to Manual, but it doesn't look like this works when editing multiple prefabs at once;

The bug is that when selecting multiple prefabs and changing the sync type, it only changes the sync type on one of the prefabs, not all of them as you'd expect.

**Comment by MMMaellon** [comment]
Are you changing the scripts in the project window? Does doing it in the hierarchy have the same issue?

**Comment by Enverex** [comment]
Yes, as doing bulk changes like this can only be done from the project window (the act of selecting many different base prefabs).

**Comment by MMMaellon** [comment]
Closing this because I don't think it's an issue with my component. The sync method is defined by Udon behavior.

The workaround is to not use the project panel to change the sync method. Click your object in your heirarchy or open your prefab first and then change it.

**Comment by Enverex** [comment]
So just to clarify, it will never be possible to do this in bulk?

**Comment by MMMaellon** [comment]
No I was saying it wasn't a problem with my code, it's an issue with VRChat's code in UdonBehaviour. However, I think it's been patched if you're on the latest SDK because I can't recreate the issue anymore

**Comment by Enverex** [comment]
Logged to the VRC-Canny as this isn't really a LightSync issue:
https://feedback.vrchat.com/sdk-bug-reports/p/changing-udon-sync-method-on-prefab-doesnt-trigger-prefab-save
